-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.

CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    user_address VARCHAR(255) NOT NULL,
    user_city VARCHAR(255) NOT NULL,
    user_state VARCHAR(255) NOT NULL,
    balance DECIMAL(12, 2) NOT NULL,
);

CREATE TABLE Categories (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL PRIMARY KEY
);

CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    description VARCHAR(255),
    img_url VARCHAR(511),
    price DECIMAL(12,2) NOT NULL,
    category VARCHAR(255),
    FOREIGN KEY (category) REFERENCES Categories(name)
);

CREATE TABLE Purchases (
    id INT NOT NULL PRIMARY KEY REFERENCES OrderHistory(order_number),
    uid INT NOT NULL REFERENCES Users(id),
    total_price DECIMAL(12,2) NOT NULL,
    num_of_items INT NOT NULL,
    order_status VARCHAR(255) NOT NULL,
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE Cart(
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    sellerid INT NOT NULL REFERENCES Users(id)
    quantity INT NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    PRIMARY KEY(uid, pid, sellerid)
);

CREATE TABLE OrderHistory(
    uid INT NOT NULL REFERENCES Users(id),
    order_number INT NOT NULL,
    pid INT NOT NULL REFERENCES Products(id)
    sellerid INT NOT NULL REFERENCES Users(id)
    quantity INT NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    fullfilldate timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    PRIMARY KEY(uid,order_number, pid, sellerid)
);

CREATE TABLE Inventory(
    pid INT NOT NULL REFERENCES Products(id),
    sid INT NOT NULL REFERENCES Seller(id),
    price DECIMAL(12,2) NOT NULL,
    quantity INT NOT NULL,
    PRIMARY KEY(pid, sid)
);

CREATE TABLE Seller(
    uid INT NOT NULL REFERENCES Users(id),
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY(uid)
);

CREATE TABLE Sales(
    buyer_id INT NOT NULL REFERENCES Users(id),
    sid INT NOT NULL REFERENCES Seller(id),
    date-time REFERENCES Purchases(time_purchased),
    fulfilled BOOLEAN,
    product_id REFERENCES Products(id),
    buyer_address VARCHAR(255),
    PRIMARY KEY(buyer_id,sid,date-time)
)
CREATE TABLE productRating (
	uid INT NOT NULL REFERENCES Users(id),
	pid INT NOT NULL REFERENCES Products(id),
	starsOutOfFive INT NOT NULL,
	ratingContent varchar(5000),
	submissionDate timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
	);
	
CREATE TABLE sellerRating (
	uid INT NOT NULL REFERENCES Users(id),
	seller_id INT NOT NULL REFERENCES Users(id),
	starsOutOfFive INT NOT NULL,
	ratingContent varchar(5000),
	submissionDate timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
	);
	
CREATE TABLE message (
	message_id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	sender_id INT NOT NULL REFERENCES Users(id),
	recipient_id INT NOT NULL REFERENCES Users(id),
	messageContent varchar(5000),
	submissionDate timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
	);
	
CREATE TABLE messageThread (
	thread_id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	sender_id INT NOT NULL REFERENCES message(sender_id),
	recipient_id INT NOT NULL REFERENCES message(recipient_id)
	);
